force-app/main/default/objects/Approval_Process_Reminder__c/Approval_Process_Reminder__c.object-meta.xml
<CustomObject>
    <label>Approval Process Reminder</label>
    <nameField>
        <label>Approval Process Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Remiders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Reminder__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Approval_Process_Remiders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Reminder__c/fields/Recipient_List__c.field-meta.xml
<CustomField>
    <fullName>Recipient_List__c</fullName>
    <label>Recipient List</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Reminder__c/fields/Recurring_Every_H__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Every_H__c</fullName>
    <description>Alert will be send every X hours</description>
    <inlineHelpText>Alert will be send every X hours</inlineHelpText>
    <label>Recurring Every (H)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Reminder__c/fields/Related_Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Related_Approval_Process__c</fullName>
    <label>Related Approval Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Reminder__c/fields/Start_Reminder_After_H__c.field-meta.xml
<CustomField>
    <fullName>Start_Reminder_After_H__c</fullName>
    <description>Start sending alerts after x hours that the approval is pending</description>
    <inlineHelpText>Start sending alerts after x hours that the approval is pending</inlineHelpText>
    <label>Start Reminder After (H)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Reminder__c/fields/Stop_Recurrence_After__c.field-meta.xml
<CustomField>
    <fullName>Stop_Recurrence_After__c</fullName>
    <description>Stop the recurrence after x alerts</description>
    <inlineHelpText>Stop the recurrence after x alerts</inlineHelpText>
    <label>Stop Recurrence After</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApprovalReminderBatch.cls
global with sharing class ApprovalReminderBatch implements mba_services.IRunAsyncJobBatch, Database.Batchable<sObject>, Database.Stateful{
    private mba_services__Async_Job__c asyncJob;
    private List<String> errors = new List<String>();
    private Integer alertSent = 0;

    global ApprovalReminderBatch() {}

    public ApprovalReminderBatch (mba_services__Async_Job__c relatedJob){
        asyncJob = relatedJob;
    }

    global Id run(mba_services__Async_Job__c relatedJob){
        return Database.executeBatch(new ApprovalReminderBatch(relatedJob), 1);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String sqlQuery =   'SELECT Id,Name,Related_Object__c,Related_Approval_Process__c,Start_Reminder_After_H__c,Business_Hours__c,Recipient_List__c,'
                        +   'Stop_Recurrence_After__c,Recurring_Every_H__c FROM Approval_Process_Reminder__c WHERE Active__c = true';
        
        return Database.getQueryLocator(sqlQuery);
    }

    global void execute(Database.BatchableContext bc, list<Approval_Process_Reminder__c> scope){
    
        for(Approval_Process_Reminder__c proc : scope){    
            Map<String, object> result = ApprovalProcessReminderService.sendApprovalProcessReminder(proc);

            if(Integer.valueOf(result.get('returnCode')) != 0){
                proc.Note__c = 'Run competed with error: ' + String.valueOf(result.get('returnMessage'));
                errors.add(proc.Name + ' ' + proc.Note__c);
            }
            else{
                proc.Note__c = 'Process last run at ' + System.now().format() + '\n' + String.valueOf(result.get('alertSent')) + ' alerts were sent.';
                alertSent += Integer.valueOf(result.get('alertSent'));
            }
        }

        update scope;
    }
    
    global void finish(Database.BatchableContext bc){
    
        String summaryMessage = 'Completed at ' + System.now().format() + '<br/>';
        summaryMessage += alertSent + ' alerts were sent<br/>';
        
        if(errors.isEmpty() == false){
            summaryMessage +=' Following error was found:<br/>';
            
            for(String strError : errors){
                summaryMessage += strError + '<br/>';
            }
        }
        
        mba_services.AsyncJobServices.closeAsyncJob(
            asyncJob.Id, 
            errors.isEmpty(), 
            summaryMessage, 
            null,
            null,
            false);
    }
}